---
- name: ZABBIX all-in-one deployment on AlmaLinux
  become: yes
  hosts: almalinux

  tasks:
    - name: Check if EPEL repo exists
      stat:
        path: /etc/yum.repos.d/epel.repo
      register: epel_repofile_result

    - name: Disable ZABBIX packages provided by EPEL
      when: epel_repofile_result.stat.exists
      lineinfile:
        dest: "/etc/yum.repos.d/epel.repo"
        line: "excludepkgs=zabbix*"
        insertafter: '^\[epel\]'
        state: present

    - name: Install zabbix repo
      dnf:
        name: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm
        state: present 
        disable_gpg_check: true

    - name: clean DNF package cache
      command: dnf clean all
              
    - name: dnf update
      dnf:
        name: "*"
        state: latest


- name: Install zabbix-server
  hosts: zabbixserver-alma
  become: yes
  tasks:
    # Didn't install zabbix-selinux-policy
    - name: install zabbix server
      dnf:
        update_cache: yes
        name: 
          - zabbix-selinux-policy
          - zabbix-agent
          - zabbix-server-mysql
          - zabbix-web-mysql 
          - zabbix-apache-conf 
          - zabbix-sql-scripts 
          - glibc-langpack-en # for en_US locale
        state: present

    - name: Add DB password to zabbix_server.conf
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf 
        regexp: "^# DBPassword="
        line: DBPassword=zabbix
        state: present

    - name: Change DBHost in zabbix_server.conf
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf 
        regexp: "^# DBHost="
        line: DBHost=192.168.56.42
        state: present

    - name: Start and enable zabbix agent 
      tags: services
      service:
        name: zabbix-agent
        state: started 
        enabled: yes
    
    - name: Configure zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "^Server="
        line: Server=192.168.56.41
        state: present

    - name: Disable SELinux 
      lineinfile:
        path: /etc/selinux/config
        regexp: "^SELINUX="
        line: SELINUX=disabled
        state: present

    - name: Start and enable zabbix server 
      tags: services
      service:
        name: zabbix-server
        state: started 
        enabled: yes
    
    - name: Unconditional reboot
      ansible.builtin.reboot: 

  handlers:
    - name: restart_zabbix_server
      service:
        name: zabbix-server
        state: restarted
    


- name: Install and configure MySQL
  hosts: zabbixdb-alma
  become: yes
  tasks:
    - name: install MySQL for ZABBIX
      dnf:
        update_cache: yes
        name: 
          - zabbix-selinux-policy
          - mysql
          - mysql-server
          - zabbix-agent
          - zabbix-sql-scripts 
          - python3-pip  
          - glibc-langpack-en # for en_US locale
        state: present

    - name: Start mysql service
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install pymysql module
      pip:
        name: pymysql
        state: present

    - name: Create Zabbix db
      mysql_db:
        name: zabbix
        encoding: utf8mb4
        collation: utf8mb4_bin
        state: present

    - name: Create Zabbix user and grant privileges
      tags: user
      mysql_user:
        name: zabbix
        password: zabbix
        login_user: root
        login_password: ""
        host: "%"  
        priv:
          'zabbix.*': 'ALL,GRANT'
        state: present

    - name: Set global log_bin_trust_function_creators
      mysql_variables:
        variable: log_bin_trust_function_creators
        value: 1
        login_user: root
        login_password: ""

    - name: Import zabbix db
      tags: import
      shell: sh -c 'zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -u zabbix -pzabbix zabbix || /bin/true'
      
    - name: timeout
      wait_for:
        timeout: 35

    - name: Wait 15 seconds
      pause:
        seconds: 15

    - name: Disable log_bin_trust_function_creators 
      mysql_variables:
        variable: log_bin_trust_function_creators
        value: 0
        login_user: root
        login_password: ""
    
    - name: Disable SELinux 
      lineinfile:
        path: /etc/selinux/config
        regexp: "^SELINUX="
        line: SELINUX=disabled
        state: present

    - name: Unconditional reboot
      ansible.builtin.reboot:

    - name: Start and enable zabbix agent 
      tags: services
      service:
        name: zabbix-agent
        state: started 
        enabled: yes

    
- name: Install and configure Apache
  hosts: zabbixfront-alma
  become: yes
  tasks:
    - name: Install Apache for ZABBIX
      dnf:
        update_cache: yes
        name: 
          - zabbix-selinux-policy
          - zabbix-agent
          - zabbix-web-mysql 
          - zabbix-apache-conf 
          - glibc-langpack-en # for en_US locale
        state: present
    
    - name: Copy setup wizard config
      tags: copy
      copy:
        src: zabbix-alma-3.conf.php
        dest: /etc/zabbix/web/zabbix.conf.php
        owner: apache
        group: apache
        mode: 0600

    - name: Set httpd_can_network_connect_db flag on and keep it persistent across reboots
      command: setsebool -P httpd_can_network_connect_db on

    - name: Set httpd_can_connect_zabbix flag on and keep it persistent across reboots
      command: setsebool -P httpd_can_connect_zabbix on

    - name: Start and enable zabbix agent 
      tags: services
      service:
        name: zabbix-agent
        state: started 
        enabled: yes
    
    - name: Start and enable apache
      tags: services
      service:
        name: httpd
        state: started 
        enabled: yes

    - name: Start and enable php-fpm
      tags: services
      service:
        name: php-fpm
        state: started 
        enabled: yes