---
- name: ZABBIX all-in-one deployment on AlmaLinux
  become: yes
  hosts: alma-allinone

  pre_tasks:
    - name: Check if EPEL repo exists
      stat:
        path: /etc/yum.repos.d/epel.repo
      register: epel_repofile_result

    - name: Disable ZABBIX packages provided by EPEL
      when: epel_repofile_result.stat.exists
      lineinfile:
        dest: "/etc/yum.repos.d/epel.repo"
        line: "excludepkgs=zabbix*"
        insertafter: '^\[epel\]'
        state: present
      


    - name: Install zabbix repo
      dnf:
        name: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm
        state: present 
        disable_gpg_check: true

    - name: clean DNF package cache
      command: dnf clean all
              
    - name: dnf update
      dnf:
        name: "*"
        state: latest


  tasks:
    ##########################################
    # Install Zabbix server, frontend, agent #
    ##########################################
    - name: install zabbix server, frontend, agent
      dnf:
        update_cache: yes
        name: 
          - zabbix-agent
          - zabbix-server-mysql
          - zabbix-web-mysql 
          - zabbix-apache-conf 
          - zabbix-sql-scripts 
          - zabbix-selinux-policy 
          - zabbix-agent
          - mysql
          - mysql-server
          - python3-pip
          - glibc-langpack-en # for en_US locale
        state: present

    - name: Start mysql service
      service:
        name: mysqld
        state: started

    - name: Install pymysql module
      pip:
        name: pymysql
        state: present

    ###########################
    # Create initial database #
    ###########################
    - name: Create Zabbix db
      mysql_db:
        name: zabbix
        encoding: utf8mb4
        collation: utf8mb4_bin
        state: present

    - name: Create Zabbix user and grant privileges
      mysql_user:
        name: zabbix
        password: zabbix
        login_user: root
        login_password: ""
        host: localhost
        priv:
          'zabbix.*': 'ALL,GRANT'
        state: present

    - name: Set global log_bin_trust_function_creators
      mysql_variables:
        variable: log_bin_trust_function_creators
        value: 1
        login_user: root
        login_password: ""

    - name: Import zabbix db
      tags: import
      shell: sh -c 'zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -u zabbix -pzabbix zabbix || /bin/true'
      
    - name: timeout
      wait_for:
        timeout: 35

    - name: Wait 15 seconds
      pause:
        seconds: 15

    - name: Disable log_bin_trust_function_creators 
      mysql_variables:
        variable: log_bin_trust_function_creators
        value: 0
        login_user: root
        login_password: ""


    ############################################
    # Configure the database for Zabbix server #
    ############################################

    - name: Add DB password to zabbix_server.conf
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf 
        regexp: "^# DBPassword="
        line: DBPassword=zabbix
        state: present


    ###########################################
    # Start Zabbix server and agent processes #
    ###########################################

    - name: Start and enable zabbix server 
      tags: services
      service:
        name: zabbix-server
        state: started 
        enabled: yes
    - name: Start and enable zabbix agent 
      tags: services
      service:
        name: zabbix-agent
        state: started 
        enabled: yes
    - name: Start and enable apache
      tags: services
      service:
        name: httpd
        state: started 
        enabled: yes
    - name: Start and enable php-fpm
      tags: services
      service:
        name: php-fpm
        state: started 
        enabled: yes
