---
- name: Zabbix deployment + Grafana integration
  hosts: allinone
  become: yes
  
  vars_files:
    - my_vault.yml
    - vars.yml
    
  vars:
    - ansible_become_pass: "{{ su_password }}"

  pre_tasks:
    # [WARNING]: Module remote_tmp /root/.ansible/tmp did not exist and was created
    # with a mode of 0700, this may cause issues when running as another user. To
    # avoid this, create the remote_tmp dir with the correct permissions manually
    - name: Create remote_tmp directory
      ansible.builtin.file:
        path: /root/.ansible/remote_tmp
        state: directory
        mode: "1777"
  
  roles:
    - debian
    - zabbix
    - postgresql
    - nginx-zabbix
    - grafana