---
- name: Grafana & Zabbix integration
  hosts: grafana
  become: yes

  vars_files:
    - my_vault.yml
  vars:
    - ansible_become_pass: "{{ su_password }}"

  pre_tasks:
    - name: Ensure the locale exists
      tags: locale
      locale_gen:
        name: en_US.UTF-8
        state: present
    - name: set default locale
      tags: locale
      command: localectl set-locale LANG=en_US.UTF-8
      changed_when: false

    - name: install updates
      tags: apt,package
      apt:
        upgrade: yes
        update_cache: yes

  tasks:
    - name: install Grafana package
      apt:
        deb: https://dl.grafana.com/enterprise/release/grafana-enterprise_10.0.2_amd64.deb

    - name: Start and enable Grafana
      service:
        name: grafana-server
        state: started
        enabled: yes

    - name: Install/update Grafana Zabbix plugin
      community.grafana.grafana_plugin:
        name: alexanderzobnin-zabbix-app
        version: latest
        state: present
    - name: Install/update Grafana piechart panel plugin
      community.grafana.grafana_plugin:
        name: grafana-piechart-panel
        version: latest
        state: present



    - name: Change owner of plugins dir
      file:
        path: /var/lib/grafana/plugins/alexanderzobnin-zabbix-app
        owner: grafana
        group: grafana
        mode: 0750
