---
- name: Install Zabbix repository
  tags: package
  apt:
    deb: https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian12_all.deb

- name: Update cache
  tags: package
  apt:
    update_cache: yes

- name: Install zabbix server
  tags: package
  apt: 
    name:
      - zabbix-server-pgsql
      - zabbix-agent

- name: Configure the database for ZABBIX server - set password
  tags: config
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf 
    regexp: "^# DBPassword="
    line: DBPassword=zabbix
    state: present